---
- name: Adjust /etc/network/interfaces (Ubuntu/Debian)
  lineinfile:
    path: /etc/network/interfaces
    regexp: "^source /etc/network/interfaces.d"
    state: absent

- name: Adjust /etc/network/interfaces (Ubuntu/Debian)
  lineinfile:
    path: /etc/network/interfaces
    line: "source-directory interfaces.d"

- name: Create /etc/network/interfaces.d (Ubuntu/Debian)
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

- name: Deploy enslavedummy (Ubuntu/Debian)
  copy:
    src: enslavedummy
    dest: /sbin
    mode: 0755